name: SSH debug
on: push
jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup tmate sessions
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3